/**
 * Simple HTML sanitizers used to remove non-deterministic attributes
 * that can cause SSR hydration diffs (IDs, timestamps, data-reactroot, ephemeral tokens)
 */
export function sanitizeServerHtml(html: string): string {
  if (!html || typeof html !== 'string') return html;

  // Remove React data attributes (data-reactroot, data-reactid)
  let out = html.replace(/\sdata-react(?:root|id)=("[^"]*"|'[^']*'|[^\s>]+)/gi, '');

  // Remove id attributes that look autogenerated (id="id-12345" or id="rnd-...")
  out = out.replace(/\sid=\"?(?:id-|rnd-|react-)[^\"\s>]+\"?/gi, '');

  // Normalize inline timestamps common in templates (datetime="2026-..." -> datetime="")
  out = out.replace(/datetime=\"\d{4}-\d{2}-\d{2}[^\"\s>]*\"/gi, 'datetime=""');

  // Strip volatile nonce attributes used for CSP (nonce="...")
  out = out.replace(/\snonce=\"[^\"]*\"/gi, '');

  return out;
}
